spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.213.130:3306/cronjob?characterEncoding=utf-8&useSSL=false&useAffectedRows=true
    username: root
    password: 123456
server:
  port: 8081

#netty监听端口
remoting:
  address: 127.0.0.1:8088
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.distribute.remoting.bean

  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
#logging:
#  level:
#    com.distribute.remoting.mapper: debug
